import Head from "next/head";
import { Route, Routes } from "react-router";
import DropdownMenu from "../components/DropdownMenu";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>METAVERSUS | The World Of WEB3.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body>
        <main className="gradient-1 bg-no-repeat bg-cover object-contain transition-all duration-300">
          <Navbar />
          <Hero />
        </main>
      </body>
    </>
  );
}
